server:
  port: 30001
  # 在返回给页面的结果里，把错误信息添加到message里
#  error:
#    include-message: always

spring:
  application:
    name: gateway-admin
  datasource:
    url: jdbc:postgresql://localhost:5432/sonar
    username: dev
    password: 123456
    driver-class-name: org.postgresql.Driver
#logging:
#  level:
#    com.broadview.coupon: debug

# 开启所有management端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"